default: &default
  host: db
  user: rooty
  password: pass
  adapter: mysql
  migration_files_path: ../migrations

development:
  <<: *default
  db: rick_and_morty

test:
  <<: *default
  db: rick_and_morty

production:
  <<: *default
  db: rick_and_morty