version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rick_and_morty
      MYSQL_USER: rooty
      MYSQL_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  db_spec:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rick_and_morty_spec
      MYSQL_USER: rooty
      MYSQL_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5433:3306"
  api:
    build: ./app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./app/backend:/app
    tty: true
    stdin_open: true
    # If TEST=true is passed with docker-compose up, runs
    # test spec. Else run server.
    command: sh -c 'if [ "$${TEST}" = "true" ]; then crystal sam.cr spec; else crystal run src/app.cr; fi'
    environment:
      TEST: ${TEST}
