version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rick_and_morty
      MYSQL_USER: rooty
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
  api:
    build: ./app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    # Dev
    volumes:
      - ./app/backend:/app
    tty: true
    stdin_open: true
