version: '3'
services:
  db:
    image: mysql:8.0
    env_file:
      - ./env-db/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  api:
    build: ./app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./app/backend:/app
    environment:
      - CRYSTAL_PATH=/app/src
    tty: true
    stdin_open: true
    # command: crystal run src/app.cr
