version: '3'
services:
  db_spec:
    image: mysql:8.0
    env_file:
      - ./env-spec-db/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5433:3306"
  api:
    build: ./app/backend
    volumes:
      - ./app/backend:/app
    environment:
      - CRYSTAL_PATH=/app/src
    tty: true
    stdin_open: true
    depends_on:
      - db_spec
    command: crystal sam.cr spec
